#!/bin/bash
# Create encrypted password files for database deployments
# This script helps you create encrypted password files interactively

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
while getopts "e:c:h" opt; do
  case $opt in
    e) ENV=$OPTARG ;;
    c) CUSTOMER=$OPTARG ;;
    h)
      cat <<EOF
Usage: $0 -e <environment> -c <customer>

  Create encrypted password files for database deployment

  Options:
    -e <env>        Environment (dev, cert, prod)
    -c <customer>   Customer code (AM, AV, CP, NN, etc.)
    -h              Show this help message

  Example:
    $0 -e dev -c AM

  This script will:
    1. Prompt for master password (PostgreSQL: postgres)
    2. Prompt for user password (application schema/user)
    3. Encrypt both passwords using GCP KMS
    4. Save to env/<env>/<customer>/ directory

  Password files created:
    - db_master_pwd.pass    (encrypted master password)
    - db_user_pwd.pass      (encrypted application user password)

  These files are SAFE to commit to Git (encrypted with GCP KMS)

EOF
      exit 0
      ;;
    *)
      echo -e "${RED}Usage: $0 -e <environment> -c <customer>${NC}"
      echo "Use -h for help"
      exit 1
      ;;
  esac
done

if [ -z "$ENV" ] || [ -z "$CUSTOMER" ]; then
  echo -e "${RED}Error: Both -e (environment) and -c (customer) are required${NC}"
  echo ""
  echo "Usage: $0 -e <environment> -c <customer>"
  echo "Example: $0 -e dev -c AM"
  echo ""
  echo "Use -h for detailed help"
  exit 1
fi

# Validate environment
if [[ ! "$ENV" =~ ^(dev|cert|prod)$ ]]; then
  echo -e "${RED}Error: Environment must be one of: dev, cert, prod${NC}"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRET_DIR="${SCRIPT_DIR}/env/${ENV}/${CUSTOMER}"

# Create directory if it doesn't exist
if [ ! -d "$SECRET_DIR" ]; then
  echo -e "${YELLOW}Directory does not exist: $SECRET_DIR${NC}"
  echo "Creating directory..."
  mkdir -p "$SECRET_DIR"
  echo -e "${GREEN}✓ Directory created${NC}"
  echo ""
fi

# Check if encrypt.sh exists
if [ ! -f "${SCRIPT_DIR}/encrypt.sh" ]; then
  echo -e "${RED}Error: encrypt.sh not found${NC}"
  echo "Make sure encrypt.sh exists in the project root"
  exit 1
fi

chmod +x "${SCRIPT_DIR}/encrypt.sh"

echo -e "${BLUE}=========================================="
echo "Create Encrypted Password Files"
echo -e "==========================================${NC}"
echo ""
echo "Environment: ${ENV}"
echo "Customer: ${CUSTOMER}"
echo "Directory: ${SECRET_DIR}"
echo ""

# Check for db-config.yml to determine db_type
DB_CONFIG="${SECRET_DIR}/db-config.yml"
if [ -f "$DB_CONFIG" ]; then
  DB_TYPE=$(yq eval ".db.type" "$DB_CONFIG" -r 2>/dev/null || echo "unknown")
  if [ "$DB_TYPE" != "null" ] && [ "$DB_TYPE" != "unknown" ]; then
    echo -e "${GREEN}Detected database type: ${DB_TYPE}${NC}"
    echo ""
  fi
fi

echo -e "${YELLOW}You will be prompted to create 2 encrypted password files:${NC}"
echo ""
echo "1. ${GREEN}db_master_pwd.pass${NC}"
echo "   - For PostgreSQL: postgres superuser password"
echo ""
echo "2. ${GREEN}db_user_pwd.pass${NC}"
echo "   - Application schema/user password"
echo "   - Used to create database user during configuration"
echo ""
echo -e "${YELLOW}Passwords will be encrypted with GCP KMS and saved to:${NC}"
echo "   $SECRET_DIR"
echo ""
read -p "Press Enter to continue..."
echo ""

# Function to create encrypted password file
create_password_file() {
  local file_name=$1
  local description=$2
  local output_file="${SECRET_DIR}/${file_name}"

  echo -e "${BLUE}=========================================="
  echo "${description}"
  echo -e "==========================================${NC}"
  echo ""

  # Check if file already exists
  if [ -f "$output_file" ]; then
    echo -e "${YELLOW}File already exists: ${output_file}${NC}"
    echo ""
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      echo -e "${YELLOW}Skipped: ${file_name}${NC}"
      echo ""
      return
    fi
    echo ""
  fi

  # Prompt for password
  echo "Enter password (will not be displayed):"
  read -s PASSWORD
  echo ""

  if [ -z "$PASSWORD" ]; then
    echo -e "${RED}Error: Password cannot be empty${NC}"
    echo -e "${YELLOW}Skipped: ${file_name}${NC}"
    echo ""
    return
  fi

  echo "Confirm password:"
  read -s PASSWORD_CONFIRM
  echo ""

  if [ "$PASSWORD" != "$PASSWORD_CONFIRM" ]; then
    echo -e "${RED}Error: Passwords do not match${NC}"
    echo -e "${YELLOW}Skipped: ${file_name}${NC}"
    echo ""
    return
  fi

  # Encrypt and save
  echo "Encrypting password with GCP KMS..."

  # Create header comments
  cat > "$output_file" <<EOF
# ENCRYPTED PASSWORD - DO NOT EDIT MANUALLY
# Generated by: create-password-files.sh
# Environment: ${ENV}
# Customer: ${CUSTOMER}
# Created: $(date)
# Decrypt with: cat ${file_name} | ./decrypt.sh ${ENV}
#
# This file contains the encrypted password for ${description}
# It is encrypted with GCP KMS and safe to commit to Git
#
# To regenerate:
# echo "YourNewPassword" | ./encrypt.sh ${ENV} > env/${ENV}/${CUSTOMER}/${file_name}

EOF

  # Encrypt and append
  if echo -n "$PASSWORD" | "${SCRIPT_DIR}/encrypt.sh" "$ENV" >> "$output_file" 2>/dev/null; then
    echo -e "${GREEN}✓ Password encrypted and saved to: ${file_name}${NC}"
    echo ""

    # Show file info
    echo "File location: ${output_file}"
    echo "File size: $(du -h "$output_file" | cut -f1)"
    echo ""
  else
    echo -e "${RED}✗ Failed to encrypt password${NC}"
    echo ""
    echo "Possible issues:"
    echo "  1. GCP KMS key not found or not accessible"
    echo "  2. Not authenticated with gcloud"
    echo "  3. Missing permissions"
    echo ""
    echo "To debug, try manually:"
    echo "  echo \"test\" | ./encrypt.sh ${ENV}"
    echo ""
    rm -f "$output_file"
    return 1
  fi
}

# Create master password file
if ! create_password_file "db_master_pwd.pass" "Master/Superuser Password"; then
  echo -e "${RED}Failed to create master password file${NC}"
  echo "Please fix the issues and try again"
  exit 1
fi

# Create user password file
if ! create_password_file "db_user_pwd.pass" "Application User Password"; then
  echo -e "${YELLOW}Warning: Failed to create user password file${NC}"
  echo "You can create it later or continue with just the master password"
fi

# Summary
echo -e "${GREEN}=========================================="
echo "Password Files Created Successfully!"
echo -e "==========================================${NC}"
echo ""

CREATED_FILES=($(find "$SECRET_DIR" -name "*.pass" -not -name "*.example" -type f 2>/dev/null))

if [ ${#CREATED_FILES[@]} -gt 0 ]; then
  echo "Created files:"
  for file in "${CREATED_FILES[@]}"; do
    echo "  ✓ $(basename "$file")"
  done
  echo ""

  echo "Location: ${SECRET_DIR}"
  echo ""

  echo -e "${YELLOW}These files are encrypted and SAFE to commit to Git:${NC}"
  echo ""
  echo "  git add ${SECRET_DIR}/*.pass"
  echo "  git commit -m \"Add encrypted passwords for ${ENV}/${CUSTOMER}\""
  echo "  git push"
  echo ""

  echo -e "${BLUE}Next steps:${NC}"
  echo ""
  echo "1. Provision VM (auto-uploads secrets to GCP):"
  echo "   ./provision-db.sh -e ${ENV} -c ${CUSTOMER}"
  echo ""
  echo "2. Configure database (auto-reads secrets from GCP):"
  echo "   ./configuration-db.sh -e ${ENV} -c ${CUSTOMER}"
  echo ""

  echo "To verify encryption, decrypt and view password:"
  echo "  cat ${SECRET_DIR}/db_master_pwd.pass | ./decrypt.sh ${ENV}"
  echo ""
else
  echo -e "${YELLOW}No password files were created${NC}"
  echo "Please try again and ensure:"
  echo "  1. You have gcloud CLI installed and configured"
  echo "  2. GCP KMS key is set up (see secrets/kms-config.yml)"
  echo "  3. You have permissions to use the KMS key"
fi
