# terraform/templates/inventory.tpl
# Static inventory generated by Terraform
# Environment: ${environment}
# Customer: ${customer}

all:
  vars:
    ansible_user: ${ssh_user}
    ansible_ssh_private_key_file: ${ssh_private_key_path}
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    postgres_databases:
      hosts:
        ${instance_name}:
          ansible_host: ${instance_ip}

          instance_hostname: ${hostname}
          instance_external_ip: ${instance_ip}
          instance_internal_ip: ${instance_internal_ip}
          instance_zone: ${zone}
          instance_region: ${region}
          instance_project: ${project_id}

          db_environment: ${environment}
          db_customer: ${customer}
